---
title: "kMeans Palette Creation"
author: "Chris Holmes"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction
InRainbows colour palettes ...ya da ya da

## Required packages
```{r, warning=F, message=F}
library(tidyverse)
library(jpeg)
library(reshape2)
library(knitr)
```

```{r}
library(inRainbows)
```


# kMeans colour space
Define function to transform an image into tidy coordinate pairs with RGB values.
```{r}
imTransform <- function(img){
  
  i <- readJPEG(img)
  
  dim_x <- dim(i)[1]
  dim_y <- dim(i)[2]
  
  df <-
    melt(i) %>% 
    spread(Var3, value) %>% 
    rename(red="1", green="2", blue="3") %>% 
    mutate(Var1 = -Var1 + dim_y) %>% 
    rename(x=Var2, y=Var1) %>% 
    mutate(hex = pmap_chr(list(red, green, blue), rgb))
  
  df
}
```

# Read in an album cover
```{r}
im_df <- imTransform(system.file("extdata/album_covers", "the_bends.jpg", package = "inRainbows"))
head(im_df)
```

## Run kmeans
```{r}
ncols <- 5 # Number of palette colors
kMeans <- kmeans(im_df[c("red", "green", "blue")], ncols)
```

Assign mean colours to all coordinate pairs
```{r}
approxCol <- kMeans$centers[kMeans$cluster, ]
```

## Visualise palette
```{r fig.align="center", fig.width=8, fig.height=3}
par(mfrow=c(1,3))
plot(im_df$x, im_df$y, col=rgb(im_df[,3:5]), 
     asp = 1, pch=".", axes=F, xlab="", ylab="", main="Original")

plot(im_df$x, im_df$y, col=rgb(approxCol), 
     asp = 1, pch=".", axes=F, xlab="", ylab="", main="Approximate")

palette <- table(rgb(approxCol)) %>% sort(decreasing = T)
barplot(palette, col=names(palette), axes=F, border=NA, main="Palette", las=2)
```

## Wrap all into one function
```{r}
imPalette <- function(img, ncol=5, my.seed=3, ...){  
  
  i <- readJPEG(img)
  mname <- str_extract(img, "(?<=/)[^.]+")
  
  dim_x <- dim(i)[1]
  dim_y <- dim(i)[2]
  
  df <-
    melt(i) %>% 
    spread(Var3, value) %>% 
    rename(red="1", green="2", blue="3") %>% 
    mutate(Var1 = -Var1 + dim_y) %>% 
    rename(x=Var2, y=Var1) %>% 
    tbl_df()
  
  df$hex <- df %>% select(red, green, blue) %>% pmap_chr(rgb)
  
  # Run Kmeans 
  set.seed(my.seed)
  kMeans <- kmeans(df[c("red", "green", "blue")], ncol, ...)
  
  # Caluclate aproximate colours
  approxCol <- kMeans$centers[kMeans$cluster, ]
  
  # Plot
  par(mfrow=c(1,3))
  plot(df$x, df$y, col=rgb(df[,3:5]), 
       asp = 1, pch=".", axes=F, xlab="", ylab="", main="Original")
  
  plot(df$x, df$y, col=rgb(approxCol), 
       asp = 1, pch=".", axes=F, xlab="", ylab="", main="Approximate")
  
  palette <- table(rgb(approxCol)) %>% sort(decreasing = T)
  barplot(palette, col=names(palette), axes=F, border=NA, main="Palette", las=2)
  
  return(assign(x=mname, value = palette, envir = .GlobalEnv))
  }
```

## Run on all album covers
```{r fig.align="center", fig.width=8, fig.height=3}
#paste0("album_covers/",list.files("album_covers")) %>% 
#  sapply(imPalette, ncol=10) %>% 
#  invisible()
```
